/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ProgramsAccordion {
    'color': string;
    'enrol_button_color': string;
    'organization_id': string;
    'organization_name': string;
    'program': any;
  }
  interface ProgramsApi {
    'checkbox_color': string;
    'color': string;
    'enrol_button_color': string;
    'organization_id': string;
    'organization_name': string;
    'programs_height': string;
  }
}

declare global {


  interface HTMLProgramsAccordionElement extends Components.ProgramsAccordion, HTMLStencilElement {}
  var HTMLProgramsAccordionElement: {
    prototype: HTMLProgramsAccordionElement;
    new (): HTMLProgramsAccordionElement;
  };

  interface HTMLProgramsApiElement extends Components.ProgramsApi, HTMLStencilElement {}
  var HTMLProgramsApiElement: {
    prototype: HTMLProgramsApiElement;
    new (): HTMLProgramsApiElement;
  };
  interface HTMLElementTagNameMap {
    'programs-accordion': HTMLProgramsAccordionElement;
    'programs-api': HTMLProgramsApiElement;
  }
}

declare namespace LocalJSX {
  interface ProgramsAccordion extends JSXBase.HTMLAttributes<HTMLProgramsAccordionElement> {
    'color'?: string;
    'enrol_button_color'?: string;
    'organization_id'?: string;
    'organization_name'?: string;
    'program'?: any;
  }
  interface ProgramsApi extends JSXBase.HTMLAttributes<HTMLProgramsApiElement> {
    'checkbox_color'?: string;
    'color'?: string;
    'enrol_button_color'?: string;
    'organization_id'?: string;
    'organization_name'?: string;
    'programs_height'?: string;
  }

  interface IntrinsicElements {
    'programs-accordion': ProgramsAccordion;
    'programs-api': ProgramsApi;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


