/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface ProgramsAccordion {
    'color': string;
    'program': object;
  }
  interface ProgramsApi {
    'color': string;
    'organization': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLProgramsAccordionElement extends Components.ProgramsAccordion, HTMLStencilElement {}
  var HTMLProgramsAccordionElement: {
    prototype: HTMLProgramsAccordionElement;
    new (): HTMLProgramsAccordionElement;
  };

  interface HTMLProgramsApiElement extends Components.ProgramsApi, HTMLStencilElement {}
  var HTMLProgramsApiElement: {
    prototype: HTMLProgramsApiElement;
    new (): HTMLProgramsApiElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'programs-accordion': HTMLProgramsAccordionElement;
    'programs-api': HTMLProgramsApiElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface ProgramsAccordion extends JSXBase.HTMLAttributes<HTMLProgramsAccordionElement> {
    'color'?: string;
    'program'?: object;
  }
  interface ProgramsApi extends JSXBase.HTMLAttributes<HTMLProgramsApiElement> {
    'color'?: string;
    'organization'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'programs-accordion': ProgramsAccordion;
    'programs-api': ProgramsApi;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


